version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: IGS_ProductsTest/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"
    environment:
        ConnectionStrings__ProductsDb: "Server=db;Database=master;User=sa;Password=ADjh3487@^98;"
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "ADjh3487@^98"
        ACCEPT_EULA: "Y"